"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {ArrowLeft,Send,Users} from "lucide-react";
type User={id:string;name:string;username:string;avatarUrl?:string|null};type Message={id:string;text:string;createdAt:string;sender:User};
export default function GroupChat({params}:{params:Promise<{id:string}>}){const [id,setId]=useState(''),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[group,setGroup]=useState<any>(null),[error,setError]=useState('');
useEffect(()=>{params.then(x=>setId(x.id))},[params]);useEffect(()=>{if(!id)return;const load=async()=>{const gr=await fetch('/api/groups');if(gr.ok){const gj=await gr.json();setGroup((gj.groups||[]).find((x:any)=>x.id===id)||null)}const r=await fetch(`/api/groups/${id}/messages`);const j=await r.json();if(r.ok)setMessages(j.messages||[]);else setError(j.error||'Unable to load group')};load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[id]);
const send=async()=>{if(!text.trim()||!id)return;const r=await fetch(`/api/groups/${id}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});const j=await r.json();if(r.ok){setMessages(m=>[...m,j.message]);setText('')}else setError(j.error||'Unable to send')};
return <main className="simplePage darkPage"><header className="simpleTop"><Link href="/groups" className="back"><ArrowLeft size={18}/> Groups</Link><div className="topBrand"><span className="topQ">Q</span><b>Qevli</b></div></header><section className="chatPage"><div className="chatHead groupHead"><div className="avatar"><Users size={20}/></div><div><b>{group?.name||'Group chat'}</b><span>{group?.description||'Qevli community chat'}</span></div></div><div className="chatBody">{messages.length?messages.map(m=><div key={m.id} className="groupMessage"><b>{m.sender.name}</b><span>@{m.sender.username}</span><p>{m.text}</p></div>):<div className="bubble other">No messages yet. Start the group conversation.</div>}</div><div className="messageComposer"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Message the group..."/><button onClick={send}><Send size={17}/></button></div></section>{error&&<button className="toast" onClick={()=>setError('')}>{error}</button>}</main>}
