"use client";
import Link from "next/link";import {useEffect,useState} from "react";import {ArrowLeft,Bell,Heart,MessageCircle,UserPlus} from "lucide-react";
type N={id:string;type:string;message:string;createdAt:string;readAt:string|null;actor?:{name:string;username:string}};
const icon=(t:string)=>t==='COMMENT'?MessageCircle:t==='FOLLOW'?UserPlus:Heart;const ago=(d:string)=>{const m=Math.floor((Date.now()-new Date(d).getTime())/60000);return m<1?'now':m<60?`${m}m`:m<1440?`${Math.floor(m/60)}h`:`${Math.floor(m/1440)}d`};
export default function Notifications(){const [items,setItems]=useState<N[]>([]),[error,setError]=useState('');const load=async()=>{const r=await fetch('/api/notifications');if(r.status===401){location.href='/login';return}const j=await r.json();if(r.ok)setItems(j.notifications||[]);else setError(j.error||'Could not load notifications')};useEffect(()=>{
  load();
  const timer=setInterval(()=>{if(document.visibilityState==="visible")load()},15000);
  return()=>clearInterval(timer)
},[]);const read=async(id:string)=>{await fetch(`/api/notifications/${id}/read`,{method:'POST'});setItems(x=>x.map(n=>n.id===id?{...n,readAt:new Date().toISOString()}:n))};return <main className="simplePage darkPage"><header className="simpleTop"><Link href="/dashboard" className="back"><ArrowLeft size={18}/> Home</Link><div className="topBrand"><span className="topQ">Q</span><b>Qevli</b></div></header><div className="simpleWrap narrow"><div className="pageEyebrow"><Bell size={15}/> Updates</div><h1>Notifications</h1><p className="lead">See what is happening around your Qevli account.</p><section className="notificationCard">{items.length?items.map(n=>{const I=icon(n.type);return <button key={n.id} className="notificationItem" onClick={()=>read(n.id)} style={{width:'100%',background:'transparent',border:0,color:'inherit',textAlign:'left',opacity:n.readAt?.toString()?0.65:1}}><div className="avatar">{n.actor?.name?.split(' ').map(x=>x[0]).join('').slice(0,2)||'Q'}</div><div><b>{n.actor?.name||'Qevli'}</b> <span>{n.message}</span><small>{ago(n.createdAt)}</small></div><I size={18}/></button>}) : <div style={{padding:20,color:'#8193ab'}}>No notifications yet.</div>}</section></div>{error&&<button className="toast" onClick={()=>setError('')}>{error}</button>}</main>}
