import { NextRequest } from 'next/server'; import { getCurrentUser } from '@/lib/auth'; import { prisma } from '@/lib/prisma'; import { notify } from '@/lib/notifications'; import { bad, created, ok, unauthorized, serverError } from '@/lib/http'; import { cleanText } from '@/lib/validation';
import { enqueueQevliJob } from '@/lib/queue';
import { rateLimit } from '@/lib/rate-limit';
import { publishEvent } from '@/lib/event-bus';
const include={author:{select:{id:true,username:true,name:true,avatarUrl:true,verified:true}},_count:{select:{reactions:true,comments:true}}};
export async function GET(req:NextRequest){try{const me=await getCurrentUser();const url=new URL(req.url);const cursor=url.searchParams.get('cursor');const limit=Math.min(Math.max(Number(url.searchParams.get('limit')||10),1),30);const following=me?(await prisma.follow.findMany({where:{followerId:me.id},select:{followingId:true}})).map(x=>x.followingId):[];const friendships=me?(await prisma.friendship.findMany({where:{status:'ACCEPTED',OR:[{requesterId:me.id},{addresseeId:me.id}]},select:{requesterId:true,addresseeId:true}})):[];const friendIds=friendships.map(x=>x.requesterId===me!.id?x.addresseeId:x.requesterId);const friendOfFriendIds=me?Array.from(new Set((await prisma.follow.findMany({where:{followerId:{in:friendIds}},select:{followingId:true}})).map(x=>x.followingId).filter(x=>x!==me.id))):[];const authorIds=me?[me.id,...following,...friendIds,...friendOfFriendIds]:[];const verifiedAuthor:any={emailVerifiedAt:{not:null}}; const where:any=me?{OR:[{visibility:'PUBLIC',author:verifiedAuthor},{visibility:'FOLLOWERS',authorId:{in:authorIds}},{visibility:'FRIENDS',authorId:{in:friendIds}},{visibility:'FRIENDS_OF_FRIENDS',authorId:{in:[...friendIds,...friendOfFriendIds]}},{authorId:me.id}]}:{visibility:'PUBLIC',author:verifiedAuthor};const rows=await prisma.post.findMany({where,include,...(cursor?{skip:1,cursor:{id:cursor}}:{}),orderBy:{createdAt:'desc'},take:limit});return ok({posts:rows,nextCursor:rows.length===limit?rows.at(-1)?.id:null});}catch{return serverError();}}
export async function POST(req:NextRequest){try{const me=await getCurrentUser();if(!me)return unauthorized();const rl=await rateLimit(`post:${me.id}`,20,60);if(!rl.allowed)return bad('You are posting too quickly. Please wait a moment.',429);const b=await req.json();const text=cleanText(b.text,5000);const imageUrl=cleanText(b.imageUrl,2000)||null;const mediaUrl=cleanText(b.mediaUrl,2000)||null;const mediaType=['IMAGE','VIDEO'].includes(String(b.mediaType||'').toUpperCase())?String(b.mediaType).toUpperCase():null;if(!text&&!imageUrl&&!mediaUrl)return bad('Write something or add an image or video.');const visibility=['PUBLIC','FOLLOWERS','FRIENDS','FRIENDS_OF_FRIENDS'].includes(b.visibility)?b.visibility:'PUBLIC';const tags=Array.from(new Set((text.match(/#[a-zA-Z0-9_]+/g)||[]).map((x:string)=>x.slice(1).toLowerCase()))).slice(0,30);const post=await prisma.post.create({data:{authorId:me.id,text,imageUrl,mediaUrl,mediaType,visibility,hashtags:{create:tags.map(tag=>({hashtag:{connectOrCreate:{where:{tag},create:{tag}}}}))}},include});
void publishEvent({type:'post.created',id:post.id,payload:{postId:post.id,authorId:me.id}});
if(mediaUrl){ void enqueueQevliJob('qevli-media','process-post-media',{postId:post.id,ownerId:me.id,mediaUrl,mediaType}); }
return created({post});}catch{return serverError();}}
