import { NextRequest } from 'next/server';
import { getCurrentUser } from '@/lib/auth';
import { prisma } from '@/lib/prisma';

async function admin(){const me=await getCurrentUser();if(!me||me.role!=='ADMIN')return null;return me}
export async function GET(){const me=await admin();if(!me)return Response.json({error:'Forbidden'},{status:403});const sources=await prisma.officialFeedSource.findMany({orderBy:[{enabled:'desc'},{category:'asc'},{name:'asc'}],include:{_count:{select:{items:true}}}});return Response.json({sources})}
export async function POST(req:NextRequest){const me=await admin();if(!me)return Response.json({error:'Forbidden'},{status:403});try{const b=await req.json();const name=String(b.name||'').trim();const feedUrl=String(b.feedUrl||'').trim();const websiteUrl=String(b.websiteUrl||feedUrl).trim();if(!name||!feedUrl)return Response.json({error:'Name and feed URL are required.'},{status:400});const slug=String(b.slug||name).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80);const source=await prisma.officialFeedSource.create({data:{slug,name,handle:b.handle||null,feedUrl,websiteUrl,logoUrl:b.logoUrl||null,category:String(b.category||'NEWS'),country:b.country||null,sourceType:b.sourceType==='HTML'?'HTML':'RSS',enabled:b.enabled!==false}});return Response.json({source},{status:201})}catch(e){return Response.json({error:String(e).includes('Unique')?'A source with that slug already exists.':'Could not add source.'},{status:400})}}
export async function PATCH(req:NextRequest){const me=await admin();if(!me)return Response.json({error:'Forbidden'},{status:403});try{const b=await req.json();const id=String(b.id||'');if(!id)return Response.json({error:'Source id is required.'},{status:400});const source=await prisma.officialFeedSource.update({where:{id},data:{name:b.name,handle:b.handle,feedUrl:b.feedUrl,websiteUrl:b.websiteUrl,logoUrl:b.logoUrl,category:b.category,country:b.country,sourceType:b.sourceType,enabled:typeof b.enabled==='boolean'?b.enabled:undefined,syncIntervalMinutes:typeof b.syncIntervalMinutes==='number'?Math.max(5,Math.min(1440,b.syncIntervalMinutes)):undefined}});return Response.json({source})}catch{return Response.json({error:'Could not update source.'},{status:400})}}
export async function DELETE(req:NextRequest){const me=await admin();if(!me)return Response.json({error:'Forbidden'},{status:403});const id=new URL(req.url).searchParams.get('id');if(!id)return Response.json({error:'Source id is required.'},{status:400});await prisma.officialFeedSource.delete({where:{id}});return Response.json({ok:true})}
