"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, Edit3, Grid3X3, Heart, Image, Camera, ShieldCheck, BriefcaseBusiness, CheckCircle2, MapPin, GraduationCap, Building2, Globe2, Search } from "lucide-react";

type User={id:string;name:string;username:string;bio:string;role?:string;school?:string|null;schoolUrl?:string|null;workplace?:string|null;workplaceUrl?:string|null;jobTitle?:string|null;currentCity?:string|null;hometown?:string|null;website?:string|null;education?:string|null;interests?:string|null;avatarUrl?:string|null;coverUrl?:string|null;professionalMode:boolean;verified:boolean;profileVisibility?:string;coinBalance?:number};
type Post={id:string;text:string;createdAt:string;imageUrl?:string|null;mediaUrl?:string|null;mediaType?:string|null;author?:{id:string};_count:{reactions:number;comments:number}};
type Progress={id:string;title:string;progress:number;goal:number};
type Suggestion={name:string;description?:string;url?:string;source:string};
const initials=(u:User)=>u.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
async function upload(file:File){const fd=new FormData();fd.append('file',file);const r=await fetch('/api/uploads',{method:'POST',body:fd});const raw=await r.text();let j:any={};try{j=raw?JSON.parse(raw):{}}catch{throw new Error(r.status===413?'Video is too large for this upload. Please choose a smaller video.':`Upload failed (${r.status}).`)}if(!r.ok)throw new Error(j.error||'Upload failed');return j;}

export default function Profile(){
 const [me,setMe]=useState<User|null>(null),[posts,setPosts]=useState<Post[]>([]),[edit,setEdit]=useState(false),[name,setName]=useState(''),[bio,setBio]=useState(''),[school,setSchool]=useState(''),[schoolUrl,setSchoolUrl]=useState(''),[workplace,setWorkplace]=useState(''),[workplaceUrl,setWorkplaceUrl]=useState(''),[jobTitle,setJobTitle]=useState(''),[currentCity,setCurrentCity]=useState(''),[hometown,setHometown]=useState(''),[website,setWebsite]=useState(''),[education,setEducation]=useState(''),[interests,setInterests]=useState(''),[professional,setProfessional]=useState(false),[verified,setVerified]=useState(false),[profileVisibility,setProfileVisibility]=useState('PUBLIC'),[weekly,setWeekly]=useState<Progress[]>([]),[daily,setDaily]=useState<Progress[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[cropSrc,setCropSrc]=useState<string|null>(null),[cropZoom,setCropZoom]=useState(1),[lookupType,setLookupType]=useState<'school'|'workplace'|null>(null),[suggestions,setSuggestions]=useState<Suggestion[]>([]);
const load=async()=>{const a=await fetch('/api/users/me');if(!a.ok){location.href='/login';return}const aj=await a.json();const u=aj.user as User;setMe(u);setName(u.name);setBio(u.bio||'');setSchool(u.school||'');setSchoolUrl(u.schoolUrl||'');setWorkplace(u.workplace||'');setWorkplaceUrl(u.workplaceUrl||'');setJobTitle(u.jobTitle||'');setCurrentCity(u.currentCity||'');setHometown(u.hometown||'');setWebsite(u.website||'');setEducation(u.education||'');setInterests(u.interests||'');setProfessional(!!u.professionalMode);setVerified(!!u.verified);setProfileVisibility(u.profileVisibility||'PUBLIC');const [p,pr]=await Promise.all([fetch('/api/posts?limit=50'),fetch('/api/professional')]);if(p.ok){const j=await p.json();setPosts((j.posts||[]).filter((x:Post)=>x.author?.id===u.id))}if(pr.ok){const j=await pr.json();setWeekly(j.weekly||[]);setDaily(j.dailyTasks||[]);setProfessional(!!j.professionalMode)}};
 useEffect(()=>{void load()},[]);
 const save=async()=>{setBusy(true);const r=await fetch('/api/users/me',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,bio,school,schoolUrl,workplace,workplaceUrl,jobTitle,currentCity,hometown,website,education,interests,profileVisibility})});const j=await r.json();setBusy(false);if(r.ok){setMe(j.user);setEdit(false);setSuggestions([])}else setError(j.error||'Could not update profile')};
 const toggleProfessional=async()=>{const next=!professional;const r=await fetch('/api/professional',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({professionalMode:next})});const j=await r.json();if(r.ok){setProfessional(next);setMe(x=>x?{...x,professionalMode:next}:x);void load()}else setError(j.error||'Could not change professional mode')};
 const changeMedia=async(type:'avatar'|'cover',file:File)=>{if(type==='avatar'){setCropZoom(1);setCropSrc(URL.createObjectURL(file));return}try{setBusy(true);const u=await upload(file);const r=await fetch('/api/users/me',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({coverUrl:u.url})});const j=await r.json();if(r.ok)setMe(j.user);else setError(j.error||'Could not save image')}catch(e){setError(e instanceof Error?e.message:'Upload failed')}finally{setBusy(false)}};
 const saveCroppedAvatar=async()=>{if(!cropSrc)return;try{setBusy(true);const img=new window.Image();img.src=cropSrc;await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=()=>reject(new Error('Could not read image'))});const side=Math.min(img.naturalWidth,img.naturalHeight)/cropZoom;const sx=(img.naturalWidth-side)/2;const sy=(img.naturalHeight-side)/2;const canvas=document.createElement('canvas');canvas.width=512;canvas.height=512;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Could not prepare image');ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(img,sx,sy,side,side,0,0,512,512);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',0.9));if(!blob)throw new Error('Could not create cropped image');const file=new File([blob],'qevli-avatar.jpg',{type:'image/jpeg'});const u=await upload(file);const r=await fetch('/api/users/me',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({avatarUrl:u.url})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Could not save profile picture');setMe(j.user);URL.revokeObjectURL(cropSrc);setCropSrc(null)}catch(e){setError(e instanceof Error?e.message:'Could not crop image')}finally{setBusy(false)}};
 const cancelCrop=()=>{if(cropSrc)URL.revokeObjectURL(cropSrc);setCropSrc(null);setCropZoom(1)};
 const lookup=async(type:'school'|'workplace',q:string)=>{setLookupType(type);if(q.trim().length<2){setSuggestions([]);return}try{const r=await fetch(`/api/profile/lookup?type=${type}&q=${encodeURIComponent(q)}`);const j=await r.json();setSuggestions(r.ok?j.results||[]:[])}catch{setSuggestions([])}};
 const choose=(s:Suggestion)=>{if(lookupType==='school'){setSchool(s.name);setSchoolUrl(s.url||'')}else{setWorkplace(s.name);setWorkplaceUrl(s.url||'')}setSuggestions([])};
 return <main className="simplePage profilePage"><header className="simpleTop"><Link href="/dashboard" className="back"><ArrowLeft size={18}/> Home</Link><div className="topBrand"><span className="topQ">Q</span><b>Qevli</b></div></header><div className="profileShell"><div className="profileCover" style={me?.coverUrl?{backgroundImage:`url(${me.coverUrl})`,backgroundSize:'cover',backgroundPosition:'center'}:{}}><label className="mediaEdit"><Camera size={15}/> Cover<input type="file" accept="image/*" hidden onChange={e=>e.target.files?.[0]&&changeMedia('cover',e.target.files[0])}/></label></div><div className="profileInfo"><div className="profileAvatarWrap"><div className="avatar profileAvatar">{me?.avatarUrl?<img src={me.avatarUrl} alt="" className="avatarImg"/>:me?initials(me):'Q'}</div><label className="avatarEdit"><Camera size={14}/><input type="file" accept="image/*" hidden onChange={e=>e.target.files?.[0]&&changeMedia('avatar',e.target.files[0])}/></label></div><div className="profileMain"><div className="profileTitle"><div><h1>{me?.name||'Loading...'} {verified&&<ShieldCheck className="blue" size={18}/>}</h1><p>{me?'@'+me.username:''}</p></div><button onClick={()=>setEdit(!edit)}><Edit3 size={16}/> {edit?'Close':'Edit profile'}</button></div>{edit?<div className="profileEditGrid">
  <label>Full name<input value={name} onChange={e=>setName(e.target.value)}/></label>
  <label>Bio<textarea value={bio} onChange={e=>setBio(e.target.value)}/></label>
  <div className="lookupField"><label>School / university<input value={school} onChange={e=>{setSchool(e.target.value);void lookup('school',e.target.value)}} onFocus={()=>{if(school)void lookup('school',school)}} placeholder="Search your school..."/></label>{lookupType==='school'&&suggestions.length>0&&<SuggestionList items={suggestions} onChoose={choose}/>}</div>
  <div className="lookupField"><label>Workplace / company<input value={workplace} onChange={e=>{setWorkplace(e.target.value);void lookup('workplace',e.target.value)}} onFocus={()=>{if(workplace)void lookup('workplace',workplace)}} placeholder="Search your workplace..."/></label>{lookupType==='workplace'&&suggestions.length>0&&<SuggestionList items={suggestions} onChoose={choose}/>}</div>
  <label>Job title<input value={jobTitle} onChange={e=>setJobTitle(e.target.value)} placeholder="e.g. Software Developer"/></label>
  <label>Current city<input value={currentCity} onChange={e=>setCurrentCity(e.target.value)} placeholder="City"/></label>
  <label>Hometown<input value={hometown} onChange={e=>setHometown(e.target.value)} placeholder="Where you're from"/></label>
  <label>Website<input value={website} onChange={e=>setWebsite(e.target.value)} placeholder="https://..."/></label>
  <label>Education / field<input value={education} onChange={e=>setEducation(e.target.value)} placeholder="e.g. Computer Science"/></label>
  <label>Profile visibility<select value={profileVisibility} onChange={e=>setProfileVisibility(e.target.value)}><option value="PUBLIC">Public</option><option value="FRIENDS">Friends</option><option value="FRIENDS_OF_FRIENDS">Friends of friends</option></select></label>
  <label>Interests<textarea value={interests} onChange={e=>setInterests(e.target.value)} placeholder="Music, gaming, technology..."/></label>
  <button className="create" onClick={save} disabled={busy}>{busy?'Saving...':'Save profile'}</button>
 </div>:<><p>{me?.bio||'Tell people a little about yourself.'}</p><div className="profileDetails">{me?.workplace&&<span><Building2 size={14}/>{me.jobTitle?`${me.jobTitle} at ${me.workplace}`:me.workplace}</span>}{me?.school&&<span><GraduationCap size={14}/>{me.school}</span>}{me?.currentCity&&<span><MapPin size={14}/>{me.currentCity}</span>}{me?.hometown&&<span><MapPin size={14}/>{me.hometown}</span>}{me?.website&&<span><Globe2 size={14}/><a href={me.website} target="_blank" rel="noreferrer">Website</a></span>}</div></>}<div className="stats"><b>{posts.length} <span>Posts</span></b><b>{me?.coinBalance||0} <span>Coins</span></b></div></div></div>
 <section className="professionalCard"><div><div className="pageEyebrow"><BriefcaseBusiness size={15}/> Creator growth</div><h2>Professional mode</h2><p>Turn it on to unlock daily tasks and weekly progress.</p></div><button className={professional?'create':'outline'} onClick={toggleProfessional}>{professional?'Professional mode ON':'Turn on professional mode'}</button></section>
 {professional&&<section className="progressGrid"><article className="simpleCard"><h2>Daily tasks</h2>{daily.map(t=><ProgressRow key={t.id} item={t}/>)}</article><article className="simpleCard"><h2>Weekly progress</h2>{weekly.map(t=><ProgressRow key={t.id} item={t}/>)}</article></section>}
 {verified&&<div className="verifiedNote"><CheckCircle2 size={18}/><span><b>Verified profile</b><small>Your verified badge was granted by a Qevli administrator after professional mode eligibility.</small></span></div>}
 <div className="profileTabs"><span><Grid3X3 size={16}/> Posts</span><span><Image size={16}/> Media</span><span><Heart size={16}/> Likes</span></div><section className="simpleCard">{posts.length?posts.map(p=><article key={p.id} style={{padding:'14px 0',borderBottom:'1px solid #1b2d46'}}><p>{p.text}</p>{(p.mediaUrl||p.imageUrl)&&p.mediaType==='VIDEO'?<video src={p.mediaUrl||p.imageUrl||''} controls style={{maxWidth:'100%',borderRadius:10}}/>:(p.mediaUrl||p.imageUrl)&&<img src={p.mediaUrl||p.imageUrl||''} alt="" style={{maxWidth:'100%',borderRadius:10}}/>}<small style={{color:'#8193ab'}}>{p._count.reactions} reactions · {p._count.comments} comments</small></article>):<><h2>Your Qevli posts</h2><p>Your published moments will appear here.</p></>}</section></div>{cropSrc&&<div className="cropOverlay" role="dialog" aria-modal="true"><div className="cropModal"><div className="cropHeader"><div><div className="pageEyebrow"><Camera size={14}/> Profile picture</div><h2>Crop your profile picture</h2><p>Adjust the zoom, then save. Qevli keeps the final picture inside the circular frame.</p></div><button className="cropClose" onClick={cancelCrop} disabled={busy}>×</button></div><div className="cropStage"><div className="cropCircle"><img src={cropSrc} alt="Profile preview" style={{transform:`scale(${cropZoom})`}}/></div></div><label className="cropZoom">Zoom <input type="range" min="1" max="3" step="0.05" value={cropZoom} onChange={e=>setCropZoom(Number(e.target.value))}/><span>{cropZoom.toFixed(1)}×</span></label><div className="cropActions"><button className="outline" onClick={cancelCrop} disabled={busy}>Cancel</button><button className="create" onClick={saveCroppedAvatar} disabled={busy}>{busy?'Saving…':'Save profile picture'}</button></div></div></div>}{error&&<button className="toast" onClick={()=>setError('')}>{error}</button>}</main>}
function SuggestionList({items,onChoose}:{items:Suggestion[];onChoose:(s:Suggestion)=>void}){return <div className="suggestions">{items.map((s,i)=><button type="button" key={`${s.name}-${i}`} onClick={()=>onChoose(s)}><Search size={14}/><span><b>{s.name}</b><small>{s.description||s.source}</small></span></button>)}</div>}
function ProgressRow({item}:{item:Progress}){const pct=Math.min(100,Math.round(item.progress/item.goal*100));return <div style={{margin:'16px 0'}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><b>{item.title}</b><span>{item.progress}/{item.goal}</span></div><div style={{height:8,borderRadius:99,background:'#1b2d46',marginTop:8,overflow:'hidden'}}><div style={{height:'100%',width:`${pct}%`,background:'linear-gradient(90deg,#2563eb,#7c3aed)'}}/></div></div>}
