"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {ArrowLeft,MessageCircle,Search,Send,Paperclip} from "lucide-react";
type User={id:string;name:string;username:string;avatarUrl?:string|null};type Conversation={id:string;members:{user:User}[];messages:{text:string;createdAt:string;senderId:string}[]};type Message={id:string;text:string;createdAt:string;senderId:string;sender:User;imageUrl?:string|null;mediaType?:string|null};
const initials=(u:User)=>u.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();const avatar=(u:User,size='avatar')=>u.avatarUrl?<img className={`${size} avatarImg`} src={u.avatarUrl} alt=""/>:<div className={size}>{initials(u)}</div>;
export default function Messages(){const [me,setMe]=useState<User|null>(null),[chats,setChats]=useState<Conversation[]>([]),[selected,setSelected]=useState<Conversation|null>(null),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(''),[username,setUsername]=useState(''),[media,setMedia]=useState<{url:string;mediaType:string}|null>(null),[error,setError]=useState('');
 useEffect(()=>{(async()=>{const a=await fetch('/api/auth/me');if(!a.ok){location.href='/login';return}const aj=await a.json();setMe(aj.user);const r=await fetch('/api/messages/conversations');if(r.ok){const j=await r.json();setChats(j.conversations||[]);if(j.conversations?.[0])select(j.conversations[0]);}})()},[]);
 useEffect(()=>{
  if(!selected?.id)return;
  const timer=setInterval(()=>{
    if(document.visibilityState!=="visible")return;
    fetch(`/api/messages/conversations/${selected.id}/messages?limit=100`,{cache:"no-store"}).then(async r=>{if(r.ok){const j=await r.json();setMessages(j.messages||[])}}).catch(()=>{})
  },3000);
  return()=>clearInterval(timer)
 },[selected?.id]);
 useEffect(()=>{
  const timer=setInterval(()=>{
    if(document.visibilityState!=="visible")return;
    fetch('/api/messages/conversations',{cache:'no-store'}).then(async r=>{if(r.ok){const j=await r.json();setChats(j.conversations||[])}}).catch(()=>{})
  },10000);
  return()=>clearInterval(timer)
 },[]);
 const select=async(c:Conversation)=>{setSelected(c);const r=await fetch(`/api/messages/conversations/${c.id}/messages`);if(r.ok){const j=await r.json();setMessages(j.messages||[])} };
 const start=async()=>{if(!username.trim())return;const r=await fetch('/api/messages/conversations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:username.trim()})});const j=await r.json();if(!r.ok){setError(j.error||'Could not start conversation');return}setUsername('');const rr=await fetch('/api/messages/conversations');const jj=await rr.json();setChats(jj.conversations||[]);const c=(jj.conversations||[]).find((x:Conversation)=>x.id===j.conversation.id)||j.conversation;select(c);};
 const attach=async(file:File)=>{const fd=new FormData();fd.append('file',file);const r=await fetch('/api/uploads',{method:'POST',body:fd});const raw=await r.text();let j:any={};try{j=raw?JSON.parse(raw):{}}catch{setError(r.status===413?'Video is too large for this upload. Please choose a smaller video.':'Upload failed.');return}if(r.ok)setMedia(j);else setError(j.error||'Upload failed')}; const send=async()=>{if(!selected||(!text.trim()&&!media))return;const r=await fetch(`/api/messages/conversations/${selected.id}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:text.trim(),mediaUrl:media?.url||null,mediaType:media?.mediaType||null})});const j=await r.json();if(r.ok){setMessages(m=>[...m,j.message]);setText('');setMedia(null)}else setError(j.error||'Unable to send message')};
 const other=(c:Conversation)=>c.members.find(m=>m.user.id!==me?.id)?.user||c.members[0]?.user;
 return <main className="simplePage darkPage"><header className="simpleTop"><Link href="/dashboard" className="back"><ArrowLeft size={18}/> Home</Link><div className="topBrand"><span className="topQ">Q</span><b>Qevli</b></div></header><div className="messageShell"><aside className="chatList"><h1>Messages</h1><div className="exploreSearch"><Search size={16}/><input value={username} onChange={e=>setUsername(e.target.value)} onKeyDown={e=>e.key==='Enter'&&start()} placeholder="Enter username to message..."/><button onClick={start} style={{border:0,background:'transparent',color:'#6da8ff',cursor:'pointer'}}>Start</button></div>{chats.map(c=>{const u=other(c);return <button className="chatItem" key={c.id} onClick={()=>select(c)}>{u?avatar(u):<div className="avatar">?</div>}<div><b>{u?.name||'Conversation'}</b><span>{c.messages?.[0]?.text||'No messages yet'}</span></div></button>})}</aside><section className="chatWindow">{selected&&other(selected)?<><div className="chatHead">{avatar(other(selected)!)}<div><b>{other(selected)!.name}</b><span>@{other(selected)!.username}</span></div></div><div className="chatBody">{messages.length?messages.map(m=><div key={m.id} className={m.senderId===me?.id?'bubble meBubble':'bubble other'}>{m.text}{m.imageUrl&&m.mediaType==='VIDEO'?<video controls src={m.imageUrl} style={{maxWidth:'100%',borderRadius:8,marginTop:6}}/>:m.imageUrl&&<img src={m.imageUrl} alt="" style={{maxWidth:'100%',borderRadius:8,marginTop:6}}/>}</div>):<div className="bubble other">Start the conversation.</div>}</div><div className="messageComposer"><label style={{cursor:'pointer'}} title="Attach photo or video"><Paperclip size={18}/><input type="file" hidden accept="image/*,video/mp4,video/webm,video/quicktime" onChange={e=>e.target.files?.[0]&&attach(e.target.files[0])}/></label><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Write a message..."/><button onClick={send}><Send size={17}/></button></div></>:<div className="chatBody"><div className="bubble other">Select a conversation or enter a Qevli username above to start one.</div></div>}</section></div>{error&&<button className="toast" onClick={()=>setError('')}>{error}</button>}</main>}
