'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowLeft, ChevronUp, Lightbulb } from 'lucide-react';

type Request = { id: string; title: string; description?: string | null; category: string; status: string; voteCount: number; voted: boolean; createdAt: string; user: { name: string; username: string; avatarUrl?: string | null } };
const tabs = [['ALL', 'All'], ['PLANNED', 'Planned'], ['IN_PROGRESS', 'In Progress'], ['DONE', 'Done']];

export default function Feedback() {
  const [requests, setRequests] = useState<Request[]>([]), [title, setTitle] = useState(''), [description, setDescription] = useState(''), [category, setCategory] = useState('FEATURE'), [tab, setTab] = useState('ALL'), [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  const load = async () => { const response = await fetch(`/api/feedback?status=${tab}`, { cache: 'no-store' }); if (response.ok) setRequests((await response.json()).requests || []); };
  useEffect(() => { void load(); }, [tab]);
  const post = async () => { setBusy(true); const response = await fetch('/api/feedback', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title, description, category }) }); const data = await response.json(); if (!response.ok) setMessage(data.error || 'Could not post request.'); else { setTitle(''); setDescription(''); setMessage('Request posted.'); await load(); } setBusy(false); };
  const vote = async (requestId: string) => { const response = await fetch('/api/feedback', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ requestId }) }); if (!response.ok) return; const data = await response.json(); setRequests(items => items.map(item => item.id === requestId ? { ...item, voted: data.voted, voteCount: data.voteCount } : item).sort((a, b) => b.voteCount - a.voteCount)); };
  return <main className="simplePage darkPage"><header className="simpleTop"><Link href="/dashboard" className="back"><ArrowLeft size={18}/> Home</Link><Link href="/dashboard" className="topBrand"><span className="topQ">Q</span><b>Qevli</b></Link></header><div className="simpleWrap"><div className="pageEyebrow"><Lightbulb size={15}/> Feedback board</div><h1>What should we build next?</h1><p className="lead">Vote for features you want and help shape Qevli.</p><section className="featureCard darkCard"><label>Title<input value={title} onChange={event => setTitle(event.target.value)} placeholder="e.g. Add effects and filters" /></label><label>Description<textarea value={description} onChange={event => setDescription(event.target.value)} placeholder="Tell us what would make Qevli better" /></label><div className="profileActions"><select value={category} onChange={event => setCategory(event.target.value)}><option value="FEATURE">Feature</option><option value="BUG">Bug</option><option value="IMPROVEMENT">Improvement</option></select><button className="primaryBtn" disabled={busy || !title.trim()} onClick={post}>{busy ? 'Posting...' : 'Post request'}</button></div>{message && <div className="demoNotice">{message}</div>}</section><nav className="feedbackTabs">{tabs.map(([value, label]) => <button className={tab === value ? 'create' : 'outline'} key={value} onClick={() => setTab(value)}>{label}</button>)}</nav><section className="feedbackList">{requests.map(request => <article className="featureCard darkCard feedbackItem" key={request.id}><button className={request.voted ? 'create voteButton' : 'outline voteButton'} onClick={() => vote(request.id)}><ChevronUp size={20}/><b>{request.voteCount}</b></button><div><div className="pageEyebrow">{request.category} · {request.status.replace('_', ' ')}</div><h2>{request.title}</h2><p>{request.description}</p><small>by @{request.user.username} · {new Date(request.createdAt).toLocaleDateString()}</small></div></article>)}{!requests.length && <div className="emptyState">No requests in this view yet.</div>}</section></div></main>;
}
