import { NextRequest } from 'next/server';
import { prisma } from '@/lib/prisma';
import { ok, bad, serverError } from '@/lib/http';
import { searchWeb } from '@/lib/web-search';

const featured: Record<string,{name:string;kind:string;summary:string;url:string}> = {
  openai:{name:'OpenAI',kind:'AI company',summary:'OpenAI is an artificial intelligence research and deployment company that develops AI systems and tools such as ChatGPT and API products.',url:'https://openai.com'},
  meta:{name:'Meta Platforms',kind:'Technology company',summary:'Meta Platforms operates social and technology products including Facebook, Instagram, WhatsApp and Messenger, and develops virtual and augmented reality technologies.',url:'https://about.meta.com'},
  'elon musk':{name:'Elon Musk',kind:'Entrepreneur',summary:'Elon Musk is a technology entrepreneur and business leader associated with companies including SpaceX, Tesla, xAI and other ventures.',url:'https://www.spacex.com'}
};
type RevalidatingRequestInit = RequestInit & { next?: { revalidate: number } };
function knowledge(q:string){const key=q.toLowerCase().replace(/\s+/g,' ').trim();for(const [k,v] of Object.entries(featured))if(key===k||key.includes(k)||k.includes(key))return v;return null;}
export async function GET(req:NextRequest){try{const q=new URL(req.url).searchParams.get('q')?.trim()||'';if(q.length<2)return bad('Search query must be at least 2 characters.');const [users,posts,companies,topicPosts]=await Promise.all([prisma.user.findMany({where:{OR:[{name:{contains:q,mode:'insensitive'}},{username:{contains:q,mode:'insensitive'}}]},select:{id:true,name:true,username:true,avatarUrl:true,bio:true,verified:true,professionalMode:true},take:10}),prisma.post.findMany({where:{text:{contains:q,mode:'insensitive'}},include:{author:{select:{id:true,name:true,username:true,avatarUrl:true,verified:true}}},orderBy:{createdAt:'desc'},take:10}),prisma.company.findMany({where:{OR:[{name:{contains:q,mode:'insensitive'}},{slug:{contains:q,mode:'insensitive'}}]},take:10}),prisma.post.findMany({where:{text:{contains:'#'+q.replace(/^#/,'') ,mode:'insensitive'},visibility:'PUBLIC'},select:{text:true},take:100})]);
const topicCounts=new Map<string,number>();for(const p of topicPosts){for(const tag of p.text.match(/#[\p{L}\p{N}_]+/gu)||[]){if(tag.toLowerCase().includes(q.toLowerCase().replace(/^#/,'').toLowerCase()))topicCounts.set(tag.toLowerCase(),(topicCounts.get(tag.toLowerCase())||0)+1)}}
const topics=[...topicCounts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,10).map(([tag,count])=>({tag,count}));const webResults = await searchWeb(q, 8).catch(() => []); let info=knowledge(q); if(!info && webResults.length){ const first=webResults[0]; info={name:first.title,kind:`Web result · ${first.source}`,summary:first.snippet||`Learn more about ${first.title}.`,url:first.url}; } if(!info){try{const title=encodeURIComponent(q.replace(/\s+/g,'_'));const init:RevalidatingRequestInit={headers:{accept:'application/json'},next:{revalidate:3600}};const r=await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${title}`,init);if(r.ok){const w=await r.json();if(w.extract)info={name:w.title||q,kind:w.description||'Information',summary:w.extract,url:w.content_urls?.desktop?.page||`https://en.wikipedia.org/wiki/${title}`};}}catch{}} return ok({query:q,users,posts,companies,topics,knowledge:info,webResults});}catch{return serverError();}}
