-- Qevli V21-V30 platform infrastructure
CREATE TABLE "EmailVerificationToken" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "tokenHash" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "usedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "EmailVerificationToken_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "EmailVerificationToken_tokenHash_key" ON "EmailVerificationToken"("tokenHash");
CREATE INDEX "EmailVerificationToken_userId_expiresAt_idx" ON "EmailVerificationToken"("userId","expiresAt");
ALTER TABLE "EmailVerificationToken" ADD CONSTRAINT "EmailVerificationToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "PasswordResetToken" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "tokenHash" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "usedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PasswordResetToken_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "PasswordResetToken_tokenHash_key" ON "PasswordResetToken"("tokenHash");
CREATE INDEX "PasswordResetToken_userId_expiresAt_idx" ON "PasswordResetToken"("userId","expiresAt");
ALTER TABLE "PasswordResetToken" ADD CONSTRAINT "PasswordResetToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "UserSession" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "sessionHash" TEXT NOT NULL, "deviceName" TEXT, "ipHash" TEXT, "userAgent" TEXT, "lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "revokedAt" TIMESTAMP(3), CONSTRAINT "UserSession_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "UserSession_sessionHash_key" ON "UserSession"("sessionHash"); CREATE INDEX "UserSession_userId_lastSeenAt_idx" ON "UserSession"("userId","lastSeenAt");
ALTER TABLE "UserSession" ADD CONSTRAINT "UserSession_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "SecurityEvent" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "type" TEXT NOT NULL, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "SecurityEvent_pkey" PRIMARY KEY ("id"));
CREATE INDEX "SecurityEvent_userId_createdAt_idx" ON "SecurityEvent"("userId","createdAt"); CREATE INDEX "SecurityEvent_type_createdAt_idx" ON "SecurityEvent"("type","createdAt");
ALTER TABLE "SecurityEvent" ADD CONSTRAINT "SecurityEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "NotificationPreference" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "likes" BOOLEAN NOT NULL DEFAULT true, "comments" BOOLEAN NOT NULL DEFAULT true, "follows" BOOLEAN NOT NULL DEFAULT true, "messages" BOOLEAN NOT NULL DEFAULT true, "mentions" BOOLEAN NOT NULL DEFAULT true, "marketing" BOOLEAN NOT NULL DEFAULT false, "push" BOOLEAN NOT NULL DEFAULT false, "email" BOOLEAN NOT NULL DEFAULT false, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "NotificationPreference_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "NotificationPreference_userId_key" ON "NotificationPreference"("userId");
ALTER TABLE "NotificationPreference" ADD CONSTRAINT "NotificationPreference_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "PushSubscription" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "endpoint" TEXT NOT NULL, "p256dh" TEXT NOT NULL, "auth" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PushSubscription_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "PushSubscription_endpoint_key" ON "PushSubscription"("endpoint"); CREATE INDEX "PushSubscription_userId_idx" ON "PushSubscription"("userId");
ALTER TABLE "PushSubscription" ADD CONSTRAINT "PushSubscription_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "MediaAsset" ("id" TEXT NOT NULL, "ownerId" TEXT NOT NULL, "url" TEXT NOT NULL, "mimeType" TEXT NOT NULL, "sizeBytes" INTEGER NOT NULL, "width" INTEGER, "height" INTEGER, "durationSec" DOUBLE PRECISION, "storageKey" TEXT, "status" TEXT NOT NULL DEFAULT 'READY', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "MediaAsset_pkey" PRIMARY KEY ("id"));
CREATE INDEX "MediaAsset_ownerId_createdAt_idx" ON "MediaAsset"("ownerId","createdAt"); ALTER TABLE "MediaAsset" ADD CONSTRAINT "MediaAsset_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "AnalyticsEvent" ("id" TEXT NOT NULL, "userId" TEXT, "name" TEXT NOT NULL, "path" TEXT, "sessionId" TEXT, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AnalyticsEvent_pkey" PRIMARY KEY ("id"));
CREATE INDEX "AnalyticsEvent_name_createdAt_idx" ON "AnalyticsEvent"("name","createdAt"); CREATE INDEX "AnalyticsEvent_userId_createdAt_idx" ON "AnalyticsEvent"("userId","createdAt"); ALTER TABLE "AnalyticsEvent" ADD CONSTRAINT "AnalyticsEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE TABLE "ModerationCase" ("id" TEXT NOT NULL, "reporterId" TEXT NOT NULL, "targetId" TEXT, "postId" TEXT, "reason" TEXT NOT NULL, "details" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'OPEN', "severity" TEXT NOT NULL DEFAULT 'MEDIUM', "resolution" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "ModerationCase_pkey" PRIMARY KEY ("id"));
CREATE INDEX "ModerationCase_status_createdAt_idx" ON "ModerationCase"("status","createdAt"); CREATE INDEX "ModerationCase_targetId_createdAt_idx" ON "ModerationCase"("targetId","createdAt");
ALTER TABLE "ModerationCase" ADD CONSTRAINT "ModerationCase_reporterId_fkey" FOREIGN KEY ("reporterId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ModerationCase" ADD CONSTRAINT "ModerationCase_targetId_fkey" FOREIGN KEY ("targetId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE TABLE "Appeal" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "caseId" TEXT, "message" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'OPEN', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Appeal_pkey" PRIMARY KEY ("id")); CREATE INDEX "Appeal_userId_createdAt_idx" ON "Appeal"("userId","createdAt"); CREATE INDEX "Appeal_status_createdAt_idx" ON "Appeal"("status","createdAt"); ALTER TABLE "Appeal" ADD CONSTRAINT "Appeal_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "RecommendationFeedback" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "targetType" TEXT NOT NULL, "targetId" TEXT NOT NULL, "action" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "RecommendationFeedback_pkey" PRIMARY KEY ("id")); CREATE INDEX "RecommendationFeedback_userId_createdAt_idx" ON "RecommendationFeedback"("userId","createdAt"); CREATE INDEX "RecommendationFeedback_targetType_targetId_idx" ON "RecommendationFeedback"("targetType","targetId"); ALTER TABLE "RecommendationFeedback" ADD CONSTRAINT "RecommendationFeedback_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "SubscriptionPlan" ("id" TEXT NOT NULL, "code" TEXT NOT NULL, "name" TEXT NOT NULL, "description" TEXT NOT NULL, "priceMinor" INTEGER NOT NULL, "currency" TEXT NOT NULL DEFAULT 'NGN', "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "SubscriptionPlan_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "SubscriptionPlan_code_key" ON "SubscriptionPlan"("code");
CREATE TABLE "Subscription" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "planId" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'DISABLED', "provider" TEXT, "providerRef" TEXT, "startsAt" TIMESTAMP(3), "endsAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Subscription_pkey" PRIMARY KEY ("id")); CREATE INDEX "Subscription_userId_status_idx" ON "Subscription"("userId","status"); ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_planId_fkey" FOREIGN KEY ("planId") REFERENCES "SubscriptionPlan"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE TABLE "PaymentRecord" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "kind" TEXT NOT NULL, "amountMinor" INTEGER NOT NULL, "currency" TEXT NOT NULL DEFAULT 'NGN', "status" TEXT NOT NULL DEFAULT 'DISABLED', "provider" TEXT, "providerRef" TEXT, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "PaymentRecord_pkey" PRIMARY KEY ("id")); CREATE INDEX "PaymentRecord_userId_createdAt_idx" ON "PaymentRecord"("userId","createdAt"); CREATE INDEX "PaymentRecord_status_createdAt_idx" ON "PaymentRecord"("status","createdAt"); ALTER TABLE "PaymentRecord" ADD CONSTRAINT "PaymentRecord_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "AdCampaign" ("id" TEXT NOT NULL, "ownerId" TEXT, "name" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'DISABLED', "budgetMinor" INTEGER NOT NULL DEFAULT 0, "currency" TEXT NOT NULL DEFAULT 'NGN', "targeting" JSONB, "creative" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AdCampaign_pkey" PRIMARY KEY ("id")); CREATE INDEX "AdCampaign_status_createdAt_idx" ON "AdCampaign"("status","createdAt");
CREATE TABLE "WebhookEvent" ("id" TEXT NOT NULL, "provider" TEXT NOT NULL, "eventId" TEXT NOT NULL, "payload" JSONB NOT NULL, "processedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "WebhookEvent_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "WebhookEvent_provider_eventId_key" ON "WebhookEvent"("provider","eventId"); CREATE INDEX "WebhookEvent_provider_createdAt_idx" ON "WebhookEvent"("provider","createdAt");
INSERT INTO "SubscriptionPlan" ("id","code","name","description","priceMinor","currency","active") VALUES
('qevli_plan_creator','CREATOR','Qevli Creator','Future creator subscription plan.',0,'NGN',false),
('qevli_plan_plus','PLUS','Qevli Plus','Future premium platform plan.',0,'NGN',false)
ON CONFLICT ("code") DO NOTHING;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "emailVerifiedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "twoFactorEnabled" BOOLEAN NOT NULL DEFAULT false;
