"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, Users, Plus, MessageCircle, Search } from "lucide-react";
type Group={id:string;name:string;description:string;privacy:string;owner:{name:string;username:string};_count:{members:number;messages:number}};
export default function Groups(){const [groups,setGroups]=useState<Group[]>([]),[name,setName]=useState(""),[description,setDescription]=useState(""),[show,setShow]=useState(false),[error,setError]=useState(""),[q,setQ]=useState("");
const load=async()=>{const r=await fetch('/api/groups');if(r.ok){const j=await r.json();setGroups(j.groups||[])}};useEffect(()=>{load()},[]);
const create=async()=>{if(!name.trim())return;const r=await fetch('/api/groups',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,description})});const j=await r.json();if(!r.ok){setError(j.error||'Could not create group');return}setName('');setDescription('');setShow(false);load()};
const join=async(id:string)=>{const r=await fetch(`/api/groups/${id}/join`,{method:'POST'});const j=await r.json();if(!r.ok){setError(j.error||'Could not join group');return}load()};
const filtered=groups.filter(g=>(g.name+' '+g.description+' '+g.owner.username).toLowerCase().includes(q.toLowerCase()));
return <main className="simplePage darkPage"><header className="simpleTop"><Link href="/dashboard" className="back"><ArrowLeft size={18}/> Home</Link><div className="topBrand"><span className="topQ">Q</span><b>Qevli</b></div></header><section className="featurePage"><div className="pageHero"><div><small>COMMUNITIES</small><h1>Groups & group chat</h1><p>Find communities, join conversations and build your own Qevli group.</p></div><button className="primaryBtn" onClick={()=>setShow(!show)}><Plus size={17}/> Create group</button></div>{show&&<div className="featureCard darkCard groupCreate"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Group name"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What is this group about?"/><button className="primaryBtn" onClick={create}>Create group</button></div>}<div className="exploreSearch"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search groups..."/></div><div className="featureGrid two">{filtered.map(g=><article className="featureCard darkCard" key={g.id}><div className="featureIcon"><Users size={20}/></div><h3>{g.name}</h3><p>{g.description||'A Qevli community.'}</p><small>Owner @{g.owner.username} · {g._count.members} members · {g._count.messages} messages</small><div className="cardActions"><button className="secondaryBtn" onClick={()=>join(g.id)}>Join</button><Link className="primaryBtn" href={`/groups/${g.id}`}>Open chat <MessageCircle size={15}/></Link></div></article>)}</div>{!filtered.length&&<div className="emptyState">No groups found yet. Create the first Qevli community.</div>}</section>{error&&<button className="toast" onClick={()=>setError('')}>{error}</button>}</main>}
