"use client";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import { Search, Users, MessageCircle, Bell, Radio, Settings, Moon, Sun, Plus, Heart, Send, ShieldCheck, MoreHorizontal, Image as ImageIcon, X, ChevronDown, Menu, Globe2, Video, BriefcaseBusiness, Building2, CalendarDays, ShoppingBag, Gamepad2, Sparkles, Trophy, Clock3, LockKeyhole, Cloud, RefreshCw, Repeat2, CornerDownRight } from "lucide-react";

type User={id:string;name:string;username:string;avatarUrl?:string|null;verified?:boolean;professionalMode?:boolean;role?:string};
type Post={kind:'POST'|'REPOST';id:string;originalPostId?:string;authorId:string;text:string;imageUrl?:string|null;mediaUrl?:string|null;mediaType?:string|null;createdAt:string;author:User;_count:{reactions:number;comments:number;shares:number;reposts:number};repostAuthor?:User;repostText?:string;repostCreatedAt?:string};
type OfficialFeed={kind:'OFFICIAL';id:string;sourceName:string;sourceHandle?:string|null;sourceUrl:string;logoUrl?:string|null;title:string;body:string;mediaUrl?:string|null;mediaType?:string|null;category:string;publishedAt:string;createdAt:string;liked?:boolean;reactionType?:string|null;_count:{reactions:number;comments:number;shares:number}};
type QviewsFeed={kind:'QVIEWS';id:string;sourceName:string;sourceUrl?:string|null;logoUrl?:string|null;title:string;body:string;mediaUrl?:string|null;mediaType?:string|null;createdAt:string};
type FeedItem=Post|OfficialFeed|QviewsFeed;
type Story={id:string;text:string;mediaUrl?:string|null;mediaType?:string|null;author:User;_count?:{views:number}};
type Upload={url:string;mediaType:string};
type Contact=User&{lastSeenAt?:string|null};
type FriendRequest=User&{requestId:string};
type Trend={tag:string;count:number};
type Comment={id:string;postId:string;parentId?:string|null;text:string;createdAt:string;author:User;replies?:Comment[]};

const nav=[['Home','/dashboard'],['Explore','/explore'],['Friends','/friends'],['Groups','/groups'],['Messages','/messages'],['Calls','/calls'],['Live','/live'],['Notifications','/notifications']] as const;
const initials=(u:User)=>u.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
const ago=(d:string)=>{const m=Math.floor((Date.now()-new Date(d).getTime())/60000);return m<1?'now':m<60?`${m}m`:m<1440?`${Math.floor(m/60)}h`:`${Math.floor(m/1440)}d`};
async function upload(file:File):Promise<Upload>{const fd=new FormData();fd.append('file',file);const r=await fetch('/api/uploads',{method:'POST',body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error||'Upload failed');return j;}

export default function Dashboard(){
 const [me,setMe]=useState<User|null>(null),[posts,setPosts]=useState<FeedItem[]>([]),[stories,setStories]=useState<Story[]>([]),[incomingRequests,setIncomingRequests]=useState<FriendRequest[]>([]),[onlineContacts,setOnlineContacts]=useState<Contact[]>([]),[offlineContacts,setOfflineContacts]=useState<Contact[]>([]),[trending,setTrending]=useState<Trend[]>([]),[suggestedPeople,setSuggestedPeople]=useState<User[]>([]),[stats,setStats]=useState({unreadMessages:0,unreadNotifications:0,followers:0,following:0}),[dark,setDark]=useState(false),[modal,setModal]=useState<'post'|'story'|null>(null),[text,setText]=useState(''),[storyText,setStoryText]=useState(''),[media,setMedia]=useState<Upload|null>(null),[loading,setLoading]=useState(true),[loadingMore,setLoadingMore]=useState(false),[hasMore,setHasMore]=useState(true),[cursor,setCursor]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[newCount,setNewCount]=useState(0),[commentsOpen,setCommentsOpen]=useState<string|null>(null),[comments,setComments]=useState<Record<string,Comment[]>>({}),[commentText,setCommentText]=useState<Record<string,string>>({}),[replyTo,setReplyTo]=useState<Record<string,string|null>>({}),[commentBusy,setCommentBusy]=useState<string|null>(null),[officialCommentsOpen,setOfficialCommentsOpen]=useState<string|null>(null),[officialComments,setOfficialComments]=useState<Record<string,Comment[]>>({}),[officialCommentText,setOfficialCommentText]=useState<Record<string,string>>({}),[officialCommentBusy,setOfficialCommentBusy]=useState<string|null>(null);
 const sentinel=useRef<HTMLDivElement|null>(null); const newest=useRef<string|null>(null);
 const loadDashboard=useCallback(async()=>{try{const r=await fetch('/api/dashboard',{cache:'no-store'});if(!r.ok)return;const j=await r.json();setStats(j.stats||{});setIncomingRequests(j.incomingRequests||[]);setOnlineContacts(j.onlineContacts||[]);setOfflineContacts(j.offlineContacts||[]);setSuggestedPeople(j.suggestedPeople||[]);setTrending(j.trending||[])}catch{}},[]);
 const loadFirst=useCallback(async()=>{setLoading(true);try{const [a,b,s]=await Promise.all([fetch('/api/auth/me',{cache:'no-store'}),fetch('/api/feed?limit=12',{cache:'no-store'}),fetch('/api/stories',{cache:'no-store'})]);const aj=await a.json();if(!a.ok){location.href='/login';return}const bj=await b.json();const sj=await s.json();setMe(aj.user);setPosts(bj.posts||[]);setCursor(bj.nextCursor||null);setHasMore(Boolean(bj.hasMore));setStories(sj.stories||[]);newest.current=bj.posts?.[0]?.createdAt||bj.posts?.[0]?.repostCreatedAt||null;await loadDashboard();}catch{setError('Unable to load Qevli right now.')}finally{setLoading(false)}},[loadDashboard]);
 const loadMore=useCallback(async()=>{if(loadingMore||!hasMore||!cursor)return;setLoadingMore(true);try{const r=await fetch(`/api/feed?limit=12&cursor=${encodeURIComponent(cursor)}`,{cache:'no-store'});const j=await r.json();if(r.ok){setPosts(x=>{const seen=new Set(x.map(i=>`${i.kind}-${i.id}`));return [...x,...(j.posts||[]).filter((i:FeedItem)=>!seen.has(`${i.kind}-${i.id}`))]});setCursor(j.nextCursor||null);setHasMore(Boolean(j.hasMore));}}finally{setLoadingMore(false)}},[cursor,hasMore,loadingMore]);
 useEffect(()=>{void loadFirst();},[loadFirst]);
 useEffect(()=>{const io=new IntersectionObserver(e=>{if(e[0]?.isIntersecting)void loadMore()},{rootMargin:'700px'});if(sentinel.current)io.observe(sentinel.current);return()=>io.disconnect()},[loadMore]);
 useEffect(()=>{
  let fallbackTimer:ReturnType<typeof setInterval>|null=null;
  let source:EventSource|null=null;
  const start=()=>{
    try{
      source=new EventSource('/api/realtime/stream');
      source.addEventListener('post',()=>setNewCount(n=>Math.max(n,1)));
      source.addEventListener('message',()=>setStats(s=>({...s,unreadMessages:s.unreadMessages+1})));
      source.addEventListener('notification',()=>setStats(s=>({...s,unreadNotifications:s.unreadNotifications+1})));
      source.onerror=()=>{source?.close();source=null;if(!fallbackTimer)fallbackTimer=setInterval(async()=>{try{const n=await fetch('/api/realtime/poll',{cache:'no-store'});if(n.ok){const j=await n.json();setStats(s=>({...s,unreadMessages:j.messages??s.unreadMessages,unreadNotifications:j.notifications??s.unreadNotifications}))}}catch{}},15000)};
    }catch{}
  };
  start();
  return()=>{source?.close();if(fallbackTimer)clearInterval(fallbackTimer)};
 },[]);
 const refreshNew=async()=>{setNewCount(0);await loadFirst();window.scrollTo({top:0,behavior:'smooth'})};
 const feedActivity=async(targetType:'OFFICIAL'|'QVIEWS',targetId:string,action:'REACTION'|'SHARE'|'REPOST',reactionType='LIKE')=>{const r=await fetch('/api/feed/activity',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetType,targetId,action,reactionType})});const j=await r.json().catch(()=>({}));if(r.ok)await loadFirst();else setError(j.error||'Unable to update this activity.')};
 const officialReact=async(id:string,type='LIKE')=>{await feedActivity('OFFICIAL',id,'REACTION',type)};
 const officialShare=async(id:string)=>{await feedActivity('OFFICIAL',id,'SHARE')};
 const openOfficialComments=async(id:string)=>{setOfficialCommentsOpen(id);if(officialComments[id])return;const r=await fetch(`/api/feed/activity?targetType=OFFICIAL&targetId=${encodeURIComponent(id)}`,{cache:'no-store'});const j=await r.json().catch(()=>({}));if(r.ok)setOfficialComments(x=>({...x,[id]:j.comments||[]}));else setError(j.error||'Unable to load comments.')};
 const submitOfficialComment=async(id:string)=>{const value=(officialCommentText[id]||'').trim();if(!value)return;setOfficialCommentBusy(id);const r=await fetch('/api/feed/activity',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetType:'OFFICIAL',targetId:id,action:'COMMENT',text:value})});const j=await r.json().catch(()=>({}));setOfficialCommentBusy(null);if(r.ok){setOfficialCommentText(x=>({...x,[id]:''}));const commentsResponse=await fetch(`/api/feed/activity?targetType=OFFICIAL&targetId=${encodeURIComponent(id)}`,{cache:'no-store'});const commentsJson=await commentsResponse.json().catch(()=>({}));if(commentsResponse.ok)setOfficialComments(x=>({...x,[id]:commentsJson.comments||[]}))}else setError(j.error||'Unable to comment.')};
 const react=async(id:string,type='LIKE',targetType:'OFFICIAL'|'QVIEWS'|'POST'='POST')=>{if(targetType==='POST'){const r=await fetch(`/api/posts/${id}/reactions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type})});if(r.ok)await loadFirst();else setError('Unable to react to this post.');return}await feedActivity(targetType,id,'REACTION',type)};
 const sharePost=async(id:string,targetType:'OFFICIAL'|'QVIEWS'|'POST'='POST')=>{if(targetType!=='POST'){await feedActivity(targetType,id,'SHARE');return}const r=await fetch(`/api/posts/${id}/share`,{method:'POST'});const j=await r.json().catch(()=>({}));if(r.ok){setError('Post shared.');await loadFirst()}else setError(j.error||'Unable to share this post.')};
 const repost=async(id:string,targetType:'OFFICIAL'|'QVIEWS'|'POST'='POST')=>{if(targetType!=='POST'){await feedActivity(targetType,id,'REPOST');return}const r=await fetch(`/api/posts/${id}/repost`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({})});const j=await r.json().catch(()=>({}));if(r.ok){setError('Reposted to your feed.');await loadFirst()}else setError(j.error||'Unable to repost this post.')};
 const openComments=async(id:string,targetType:'POST'|'OFFICIAL'|'QVIEWS'='POST')=>{const key=`${targetType}:${id}`;setCommentsOpen(key);if(!comments[key]){const r=targetType==='POST'?await fetch(`/api/posts/${id}/comments`,{cache:'no-store'}):await fetch(`/api/feed/activity?targetType=${targetType}&targetId=${encodeURIComponent(id)}`,{cache:'no-store'});const j=await r.json().catch(()=>({}));if(r.ok)setComments(x=>({...x,[key]:j.comments||[]}))}};
 const submitComment=async(id:string,targetType:'POST'|'OFFICIAL'|'QVIEWS'='POST')=>{const key=`${targetType}:${id}`;const value=(commentText[key]||'').trim();if(!value)return;setCommentBusy(key);let r:Response;if(targetType==='POST')r=await fetch(`/api/posts/${id}/comments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:value,parentId:replyTo[key]||null})});else r=await fetch('/api/feed/activity',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetType,targetId:id,action:'COMMENT',text:value,parentId:replyTo[key]||null})});const j=await r.json().catch(()=>({}));setCommentBusy(null);if(r.ok){setCommentText(x=>({...x,[key]:''}));setReplyTo(x=>({...x,[key]:null}));await openComments(id,targetType)}else setError(j.error||'Unable to comment.')};
 const chooseMedia=async(file:File)=>{try{setBusy(true);setMedia(await upload(file))}catch(e){setError(e instanceof Error?e.message:'Upload failed')}finally{setBusy(false)}};
 const publish=async()=>{if(!text.trim()&&!media)return;setBusy(true);const r=await fetch('/api/posts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:text.trim(),mediaUrl:media?.url||null,mediaType:media?.mediaType||null})});const j=await r.json();setBusy(false);if(r.ok){setText('');setMedia(null);setModal(null);await loadFirst()}else setError(j.error||'Could not publish.')};
 const publishStory=async()=>{if(!storyText.trim()&&!media)return;setBusy(true);const r=await fetch('/api/stories',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:storyText.trim(),mediaUrl:media?.url||null,mediaType:media?.mediaType||null})});const j=await r.json();setBusy(false);if(r.ok){setStoryText('');setMedia(null);setModal(null);await loadFirst()}else setError(j.error||'Could not post story.')};
 const sendFriend=async(username:string,id:string)=>{const r=await fetch('/api/friends',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,action:'REQUEST'})});if(r.ok)setSuggestedPeople(x=>x.filter(p=>p.id!==id));else{const j=await r.json().catch(()=>({}));setError(j.error||'Unable to send friend request.')}};
 return <div className={dark?'app dark qevliApp':'app qevliApp'}>
  <header className="topbar"><Link href="/dashboard" className="topBrand"><span className="topQ">Q</span><b>Qevli</b></Link><form className="topSearch" onSubmit={e=>{e.preventDefault();location.href=`/explore?q=${encodeURIComponent((e.currentTarget.elements.namedItem('q') as HTMLInputElement).value)}`}}><Search size={18}/><input name="q" placeholder="Search people, posts, topics..."/></form><nav className="topActions"><Link href="/messages" className="topIcon"><MessageCircle size={21}/>{stats.unreadMessages>0&&<i>{stats.unreadMessages}</i>}</Link><Link href="/notifications" className="topIcon"><Bell size={21}/>{stats.unreadNotifications>0&&<i>{stats.unreadNotifications}</i>}</Link>{me&&<Link href="/profile" className="topProfile">{me.avatarUrl?<img className="me avatarImg" src={me.avatarUrl} alt=""/>:<div className="me">{initials(me)}</div>}<span>{me.name}</span><ChevronDown size={15}/></Link>}</nav></header>
  <aside className="sidebar"><Link href="/profile" className="sideProfile">{me?.avatarUrl?<img className="avatar sideAvatar avatarImg" src={me.avatarUrl} alt=""/>:<div className="avatar sideAvatar">{me?initials(me):'…'}</div>}<div><b>{me?.name||'Loading…'}</b><span>@{me?.username||'…'}</span></div></Link><nav className="sideNav">{nav.map(([n,h])=>{const Icon=n==='Home'?Radio:n==='Explore'?Search:n==='Friends'?Users:n==='Groups'?Users:n==='Messages'?MessageCircle:n==='Calls'?Video:n==='Live'?Radio:Bell;return <Link key={n} href={h} className={n==='Home'?'nav active':'nav'}><Icon size={19}/><span>{n}</span></Link>})}</nav><div className="sideLabel">Your Qevli</div><Link href="/companies" className="nav"><Building2 size={18}/><span>Official pages</span></Link><Link href="/events" className="nav"><CalendarDays size={18}/><span>Events</span></Link><Link href="/marketplace" className="nav"><ShoppingBag size={18}/><span>Marketplace</span></Link><Link href="/video" className="nav"><Video size={18}/><span>Qevli Video</span></Link><Link href="/gaming" className="nav"><Gamepad2 size={18}/><span>Gaming</span></Link><Link href="/ai" className="nav"><Sparkles size={18}/><span>Qevli AI</span></Link><Link href="/creator" className="nav"><BriefcaseBusiness size={18}/><span>Creator studio</span></Link><Link href="/tournaments" className="nav"><Trophy size={18}/><span>Tournaments</span></Link><Link href="/saved" className="nav"><Clock3 size={18}/><span>Saved</span></Link>{me?.role==='ADMIN'&&<Link href="/admin" className="nav"><ShieldCheck size={18}/><span>Admin center</span></Link>}<button className="create" onClick={()=>setModal('post')}><Plus size={18}/><span>Create post</span></button><div className="sideBottom"><Link href="/settings" className="nav"><Settings size={18}/><span>Settings</span></Link><button className="nav" onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}<span>{dark?'Light mode':'Dark mode'}</span></button></div></aside>
  <main className="qevliMain"><div className="mobileOnly mobileHeader"><button className="mobileMenu"><Menu/></button><Link href="/dashboard" className="topBrand"><span className="topQ">Q</span><b>Qevli</b></Link>{me&&<Link href="/profile" className="me">{initials(me)}</Link>}</div>
   <div className="qevliColumns"><section className="feed"><div className="welcomeBanner"><div className="welcomeMiniAvatar">{me?.avatarUrl?<img src={me.avatarUrl} alt=""/>:<span>{me?initials(me):'…'}</span>}</div><div className="welcomeCopy"><small>YOUR HOME FEED</small><h1>{me?`Good to see you, ${me.name.split(' ')[0]}.`:'Loading your feed…'}</h1><p>Public posts, friends, creators, Qviews and official updates — all in one live feed.</p></div><button className="storyButton" onClick={()=>setModal('story')}><Plus size={17}/> Add story</button></div>
    <div className="stories"><button className="story createStoryCard" onClick={()=>setModal('story')}><div className="storyImage createStoryImage"><span className="storyPlus">+</span></div><span className="storyLabel">Create story</span></button>{stories.map(s=><button className="story" key={s.id}><div className="storyImage" style={{backgroundImage:s.mediaUrl&&s.mediaType==='IMAGE'?`url(${s.mediaUrl})`:undefined}}>{s.mediaType==='VIDEO'&&<Video size={22}/>}<span className="storyAvatarRing">{initials(s.author)}</span></div><span className="storyLabel">{s.author.name}</span></button>)}</div>
    <div className="composer" onClick={()=>setModal('post')}>{me?.avatarUrl?<img className="avatar avatarImg" src={me.avatarUrl} alt=""/>:<div className="avatar">{me?initials(me):'…'}</div>}<span>What's on your mind?</span><button onClick={e=>{e.stopPropagation();setModal('post')}}><ImageIcon size={19}/></button></div>
    {newCount>0&&<button className="newPostsBanner" onClick={refreshNew}><RefreshCw size={15}/> {newCount===1?'1 new post':'New posts'} · refresh feed</button>}
    {loading?<div className="card" style={{padding:20}}>Loading your Qevli feed…</div>:posts.length===0?<div className="card" style={{padding:20}}>No posts or official updates yet.</div>:posts.map(p=>{const targetType=p.kind==='POST'||p.kind==='REPOST'?'POST':p.kind;const targetId=p.kind==='POST'||p.kind==='REPOST'?(p.originalPostId||p.id):p.id;const key=`${targetType}:${targetId}`;return <FeedCard key={`${p.kind}-${p.id}`} item={p} onReact={react} onShare={sharePost} onRepost={repost} onOfficialReact={officialReact} onOfficialShare={officialShare} officialCommentsOpen={officialCommentsOpen} openOfficialComments={openOfficialComments} officialComments={officialComments} officialCommentText={officialCommentText} setOfficialCommentText={v=>setOfficialCommentText(x=>({...x,[p.id]:v}))} submitOfficialComment={submitOfficialComment} officialCommentBusy={officialCommentBusy} commentsOpen={commentsOpen===key} openComments={openComments} comments={comments[key]||[]} commentText={commentText[key]||''} setCommentText={v=>setCommentText(x=>({...x,[key]:v}))} submitComment={submitComment} commentBusy={commentBusy===key} replyTo={replyTo[key]||null} setReplyTo={v=>setReplyTo(x=>({...x,[key]:v}))}/>}) }
    <div ref={sentinel} className="feedSentinel">{loadingMore?'Loading more posts…':hasMore?'Scroll for more':'You’re all caught up.'}</div></section>
   <aside className="rightColumn socialRightRail"><Card title={`Friend requests · ${incomingRequests.length}`}>{incomingRequests.length?incomingRequests.map(u=><div className="friendRequest" key={u.requestId}>{u.avatarUrl?<img className="avatar avatarImg" src={u.avatarUrl} alt=""/>:<div className="avatar">{initials(u)}</div>}<div className="friendRequestBody"><b>{u.name}</b><span>@{u.username}</span><div className="friendRequestActions"><button className="acceptBtn" onClick={async()=>{const r=await fetch('/api/friends',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u.username,action:'ACCEPT'})});if(r.ok)loadDashboard()}}>Confirm</button><button className="declineBtn" onClick={async()=>{const r=await fetch('/api/friends',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u.username,action:'DECLINE'})});if(r.ok)loadDashboard()}}>Delete</button></div></div></div>):<div className="emptySide">No new friend requests.</div>}<Link className="seeAllLink" href="/friends">See all friend requests</Link></Card>
    <Card title="People you may know"><div className="peopleMayKnow">{suggestedPeople.length?suggestedPeople.map(u=><div className="mayKnowRow" key={u.id}>{u.avatarUrl?<img className="avatar small avatarImg" src={u.avatarUrl} alt=""/>:<div className="avatar small">{initials(u)}</div>}<div className="mayKnowInfo"><Link href={`/profile/${u.username}`}><b>{u.name}</b><span>@{u.username}</span></Link><button onClick={()=>sendFriend(u.username,u.id)}>Add friend</button></div></div>):<div className="emptySide">No new people to suggest yet.</div>}</div></Card>
    <Card title="Trending on Qevli"><div className="trendRows">{trending.length?trending.map(t=><Link className="trendRowReal" key={t.tag} href={`/explore?q=${encodeURIComponent(t.tag)}`}><b>{t.tag}</b><span>{t.count} {t.count===1?'post':'posts'}</span></Link>):<div className="emptySide">Trends will appear as people post.</div>}</div></Card>
    <Card title="Contacts"><div className="contactsHeading"><span>Online</span><small>{onlineContacts.length}</small></div>{onlineContacts.map(u=><Link href={`/profile/${u.username}`} className="contact" key={u.id}>{u.avatarUrl?<img className="avatar small avatarImg" src={u.avatarUrl} alt=""/>:<div className="avatar small">{initials(u)}</div>}<div><b>{u.name}</b><span>Active now</span></div><i className="online"/></Link>)}{!onlineContacts.length&&<div className="emptySide">No friends are online right now.</div>}</Card>
    <Card title="Qviews"><div className="activity"><span>Official Qviews updates are automatically refreshed and mixed into the public feed.</span><Link href="/companies">View official page</Link></div></Card></aside></div></main>
   {modal&&<div className="overlay" onMouseDown={()=>setModal(null)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modalHead"><h2>{modal==='post'?'Create post':'Create story'}</h2><button onClick={()=>setModal(null)}><X/></button></div>{modal==='post'?<><textarea autoFocus value={text} onChange={e=>setText(e.target.value)} placeholder="What's on your mind?"/><div className="modalRow"><label className="outline"><ImageIcon size={17}/> Photo/video<input type="file" hidden accept="image/*,video/mp4,video/webm,video/quicktime" onChange={e=>e.target.files?.[0]&&chooseMedia(e.target.files[0])}/></label>{media&&<span>{media.mediaType==='VIDEO'?'Video':'Photo'} attached</span>}<button className="create smallBtn" disabled={busy} onClick={publish}>{busy?'Publishing…':'Publish'}</button></div></>:<><textarea autoFocus value={storyText} onChange={e=>setStoryText(e.target.value)} placeholder="Share a moment..."/><div className="modalRow"><label className="outline"><ImageIcon size={17}/> Photo/video<input type="file" hidden accept="image/*,video/mp4,video/webm,video/quicktime" onChange={e=>e.target.files?.[0]&&chooseMedia(e.target.files[0])}/></label>{media&&<span>Media attached</span>}</div><button className="create full" disabled={busy} onClick={publishStory}>{busy?'Posting…':'Post story'}</button></>}</div></div>}
   {error&&<button className="toast" onClick={()=>setError('')}>{error}</button>}
  </div>;
}

function FeedCard({item,onReact,onShare,onRepost,onOfficialReact,onOfficialShare,officialCommentsOpen,openOfficialComments,officialComments,officialCommentText,setOfficialCommentText,submitOfficialComment,officialCommentBusy,commentsOpen,openComments,comments,commentText,setCommentText,submitComment,commentBusy,replyTo,setReplyTo}:{item:FeedItem;onReact:(id:string,type?:string)=>void;onShare:(id:string)=>void;onRepost:(id:string)=>void;onOfficialReact:(id:string,type?:string)=>void;onOfficialShare:(id:string)=>void;officialCommentsOpen:string|null;openOfficialComments:(id:string)=>void;officialComments:Record<string,Comment[]>;officialCommentText:any;setOfficialCommentText:(v:string)=>void;submitOfficialComment:(id:string)=>void;officialCommentBusy:string|null;commentsOpen:boolean;openComments:(id:string)=>void;comments:Comment[];commentText:string;setCommentText:(v:string)=>void;submitComment:(id:string)=>void;commentBusy:boolean;replyTo:string|null;setReplyTo:(v:string|null)=>void}){
 if(item.kind==='OFFICIAL'){const o=item as OfficialFeed;const cs=officialComments[o.id]||[];return <article className="post officialFeedCard"><div className="postHead">{o.logoUrl?<img className="avatar avatarImg" src={o.logoUrl} alt=""/>:<div className="avatar officialAvatar">Q</div>}<div><b>{o.sourceName} <ShieldCheck className="blue" size={15}/></b><span>{o.sourceHandle||'Official update'} · {ago(o.publishedAt)} · <Globe2 size={11}/></span></div><span className="officialBadge">{o.category}</span></div><div className="officialBody"><h3>{o.title}</h3><p>{o.body}</p>{o.mediaUrl&&(o.mediaType==='VIDEO'?<video className="postMedia" src={o.mediaUrl} controls preload="metadata"/>:<img className="postMedia" src={o.mediaUrl} alt={o.title}/>)}<div className="engagement"><span className="reactionSummary"><b>👍</b><strong>{o._count.reactions}</strong></span><span>{o._count.comments} comments</span><span>{o._count.shares} shares</span></div><div className="actions"><button onClick={()=>onOfficialReact(o.id,'LIKE')}><Heart size={18} fill={o.liked?'currentColor':'none'}/> {o.liked?'Liked':'Like'}</button><button onClick={()=>openOfficialComments(o.id)}><MessageCircle size={18}/> Comment</button><button onClick={()=>onOfficialShare(o.id)}><Send size={18}/> Share</button><a className="primaryBtn" href={o.sourceUrl} target={o.sourceUrl.startsWith('/')?'_self':'_blank'} rel="noreferrer">View source</a></div><div className="reactionPicker">{[['👍','LIKE'],['❤️','LOVE'],['😂','HAHA'],['😮','WOW'],['😢','SAD'],['😡','ANGRY']].map(([emoji,type])=><button key={type} title={type} onClick={()=>onOfficialReact(o.id,type)}>{emoji}</button>)}</div>{officialCommentsOpen===o.id&&<div className="inlineComments"><div className="commentComposer"><div className="avatar small">Q</div><input value={officialCommentText} onChange={e=>setOfficialCommentText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submitOfficialComment(o.id)} placeholder="Write a comment..."/><button onClick={()=>submitOfficialComment(o.id)} disabled={officialCommentBusy===o.id}>{officialCommentBusy===o.id?'...':'Post'}</button></div>{cs.map(c=><CommentRow key={c.id} comment={c} onReply={()=>{}}/> )}</div>}</div></article>}
 if(item.kind==='QVIEWS'){return <article className="post officialFeedCard"><div className="postHead">{item.logoUrl?<img className="avatar avatarImg" src={item.logoUrl} alt=""/>:<div className="avatar officialAvatar">Q</div>}<div><b>{item.sourceName} <ShieldCheck className="blue" size={15}/></b><span>Official Qviews update · {ago(item.createdAt)} · <Globe2 size={11}/></span></div><span className="officialBadge">QVIEWS</span></div><div className="officialBody"><h3>{item.title}</h3><p>{item.body}</p>{item.mediaUrl&&(item.mediaType==='VIDEO'?<video className="postMedia" src={item.mediaUrl} controls preload="metadata"/>:<img className="postMedia" src={item.mediaUrl} alt={item.title}/>)}<div className="officialActions"><a className="primaryBtn" href={item.sourceUrl||'/companies/qviews'} target={(item.sourceUrl||'').startsWith('/')?'_self':'_blank'} rel="noreferrer">View Qviews update</a></div></div></article>}
 const p=item as Post; const isRepost=p.kind==='REPOST'; const targetId=p.originalPostId||p.id; return <article className="post"><div className="postHead">{(isRepost?p.repostAuthor:p.author)?.avatarUrl?<img className="avatar avatarImg" src={(isRepost?p.repostAuthor:p.author)?.avatarUrl||''} alt=""/>:<div className="avatar">{initials((isRepost?p.repostAuthor:p.author) as User)}</div>}<div><b>{(isRepost?p.repostAuthor:p.author)?.name} {((isRepost?p.repostAuthor:p.author)?.verified)&&<ShieldCheck className="blue" size={15}/>}</b><span>{isRepost?'reposted':'@'+p.author.username} · {ago(isRepost?(p.repostCreatedAt||p.createdAt):p.createdAt)} · <Globe2 size={11}/></span></div><button className="icon"><MoreHorizontal/></button></div>{isRepost&&p.repostText&&<p className="repostCaption">{p.repostText}</p>}{isRepost&&<div className="repostLabel"><Repeat2 size={14}/> Shared from @{p.author.username}</div>}<div className={isRepost?'repostOriginal':''}><div className="postInnerHead"><b>{p.author.name}</b><span>@{p.author.username}</span></div>{p.text&&<p>{p.text}</p>}{(()=>{const media=p.mediaUrl||p.imageUrl;if(!media)return null;return p.mediaType==='VIDEO'?<video className="postMedia" src={media} controls preload="metadata"/>:<img className="postMedia" src={media} alt="Qevli post"/>})()}</div><div className="engagement"><span className="reactionSummary"><b>👍</b><strong>{p._count.reactions}</strong></span><span>{p._count.comments} comments</span><span>{p._count.shares} shares</span><span>{p._count.reposts} reposts</span></div><div className="actions"><button onClick={()=>onReact(targetId,'LIKE')}><Heart size={18}/> Like</button><button onClick={()=>openComments(targetId)}><MessageCircle size={18}/> Comment</button><button onClick={()=>onShare(targetId)}><Send size={18}/> Share</button><button onClick={()=>onRepost(targetId)}><Repeat2 size={18}/> Repost</button></div><div className="reactionPicker">{[['👍','LIKE'],['❤️','LOVE'],['😂','HAHA'],['😮','WOW'],['😢','SAD'],['😡','ANGRY']].map(([emoji,type])=><button key={type} title={type} onClick={()=>onReact(targetId,type)}>{emoji}</button>)}</div>{commentsOpen&&<div className="inlineComments"><div className="commentComposer"><div className="avatar small">Q</div><input value={commentText} onChange={e=>setCommentText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submitComment(targetId)} placeholder={replyTo?'Write a reply...':'Write a comment...'}/><button onClick={()=>submitComment(targetId)} disabled={commentBusy}>{commentBusy?'...':'Post'}</button></div>{replyTo&&<button className="replying" onClick={()=>setReplyTo(null)}>Replying · cancel</button>}{comments.map(c=><CommentRow key={c.id} comment={c} onReply={()=>setReplyTo(c.id)}/>)}</div>}</article>;
}
function CommentRow({comment,onReply}:{comment:Comment;onReply:()=>void}){return <div className="commentRow"><div className="avatar tiny">{initials(comment.author)}</div><div className="commentBubble"><b>{comment.author.name}</b><span>{ago(comment.createdAt)}</span><p>{comment.text}</p><button onClick={onReply}><CornerDownRight size={12}/> Reply</button>{comment.replies?.map(r=><div className="replyRow" key={r.id}><div className="avatar tiny">{initials(r.author)}</div><div className="commentBubble"><b>{r.author.name}</b><span>{ago(r.createdAt)}</span><p>{r.text}</p></div></div>)}</div></div>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <div className="card"><div className="cardTitle"><b>{title}</b></div>{children}</div>}
